djangoMusicSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # 'music/22/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

     # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    # # 'music/22/favorite
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    #
    # # 'music/22/unfavorite
    # url(r'^(?P<album_id>[0-9]+)/unfavorite/$', views.un_favorite, name='unfavorite'),

]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html'%}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success"> Add</button>
                            </div>

                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous"> {% load staticfiles%} {% comment %}
    <link rel="stylesheet" href="{% static 'music/bootstrap.css' %}">{% endcomment %}
    <link rel="stylesheet" href="{% static 'music/style.css' %}"> {% comment %}
    <script src="{% static 'music/bootstrap.js' %}"></script>{% endcomment %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>
        {% block title %} {% endblock %} </title>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toogle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                    
                </button>
                <a href="{% url 'music:index' %}" class="navbar-brand">BeatWorker</a>
            </div>

            <!--items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span> Albums
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span> Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="GET" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                        <button type="submit" class="btn btn-default">Search</button>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Album
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
    {% block body %} {% endblock %}
</body>

</html>

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
{% extends 'music/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Album Details {% endblock %} </title>
</head>

<body>
    
     {% block body %}
          <div class="container">

     {% if error_message %}
     <p><strong>{{error_message}} </strong></p>
    {% endif %}


         <div class="col-md-4">
             <div class="row">
                    <div class="col-sm-6 col-md-10">
                        <div class="thumbnail">
                            <img src="{{ album.album_logo}}" alt="..." style="width: 250px; height: 250px;">
                            <div class="caption">
                                <h3>{{album.album_title}}</h3>
                                <span><small>{{album.genre}}</small></span>
                                <p>{{album.artist}}</p>
                            </div>
                        </div>
                     </div>
            </div>
         </div>

         <div class="col-md-8">
             <button class="btn btn-primary">View all</button>
             <span>Add New Song</span>

             <div>
                 <h2>All Songs</h2>
                 <table class="table table-striped">
                     <thead>
                     <tr>
                         <th>Title</th>
                         <th>Audio File</th>
                         <th> Favorite</th>
                         <th>Actions</th>
                     </tr>
                     </thead>
                     <tbody>
                     {% for song in album.song_set.all %}
                     <tr>
                         <td>{{ song.song_title }}</td>
                         <td> {{ song.file_type }}</td>
                         <td>{% if song.is_favorite %}
                        <img src="http://icons.iconarchive.com/icons/klukeart/pink-gold/128/star-gold-icon.png" alt="failed to load" style="width: 16px;height:16px">
                            {% endif %}</td>
                         <td></td>
                     </tr>
                     {% endfor%}
                     </tbody>

                 </table>

             </div>
         </div>
</div>
     {% endblock %}
</body>

</html>

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag}}</label>
    <div class="col-sm-10"> {{ field }}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{%block title%} Home{% endblock%}

    {% block body%}
    <div class="container">

        {% if all_albums %}
        <div class="row">
            {% for album in all_albums %}
            <div class="col-sm-6 col-md-3">
                <div class="thumbnail">
                    <img src="{{ album.album_logo}}" alt="..." style="width: 250px; height: 250px;">
                    <div class="caption">
                        <h3>{{album.album_title}}</h3>
                        <p>{{album.artist}}</p>
                        <a href="{% url 'music:detail' album.id %}" class="btn btn-primary" role="button">View Details</a>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></button>
                        <button class="btn btn-default"><span class="glyphicon glyphicon-star"></span></button>
                    </div>
                </div>
            </div>

            {% endfor %}</div> {% else %}
        <h3> no albums yet</h3>
        {% endif %}
    </div>
    {% endblock %}